# Generated by Django 6.0.7 on 2026-07-17 00:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=150)),
                ('año', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio en USD', max_digits=12)),
                ('kilometraje', models.PositiveIntegerField()),
                ('transmision', models.CharField(choices=[('automática', 'Automática'), ('sincrónica', 'Sincrónica')], max_length=20)),
                ('combustible', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('estatus', models.CharField(choices=[('disponible', 'Disponible'), ('apartado', 'Apartado'), ('vendido', 'Vendido')], default='disponible', max_length=20)),
                ('destacado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='inventario.marca')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['-destacado', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ImagenVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='vehiculos/%Y/%m/')),
                ('es_principal', models.BooleanField(default=False, help_text='Marcar si es la foto principal de portada')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización (menor = primero)')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='inventario.vehiculo')),
            ],
            options={
                'verbose_name': 'Imagen de Vehículo',
                'verbose_name_plural': 'Imágenes de Vehículos',
                'ordering': ['orden', '-es_principal', 'id'],
            },
        ),
    ]
