# Generated by Django 6.0.7 on 2026-07-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='estatus',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('no disponible', 'No Disponible')], default='disponible', max_length=20),
        ),
    ]
